use crate::tui::model::StationRow;
use radio_core::audio::Status;
use radio_core::catalog::SearchQuery;

#[derive(Debug, Clone)]
pub enum Msg {
    Quit,
    OpenSettings,
    OpenHelp,
    OpenSyncOverlay,
    CloseOverlay,
    SettingsNav(bool),
    SettingsToggle,
    SettingsAdjust(bool),
    KeybindNav(bool),
    KeybindStartCapture,
    CaptureKey(crate::tui::keybind::KeyChord),
    KeybindReset,
    SelectNext,
    SelectPrev,
    SelectPageDown,
    SelectPageUp,
    EnterSearch,
    SearchChar(char),
    SearchBackspace,
    SearchClear,
    SubmitSearch,
    PlaySelected,
    Shuffle,
    CycleSort,
    ToggleHideUnplayable,
    Stop,
    SyncNow,
    SyncCreate,
    SyncCopy,
    SyncLogout,
    SyncDelete,
    SyncKeyChanged(Option<String>),
    Notice(String),
    ToggleFavoriteSelected,
    BlacklistSelected,
    RecheckSelected,
    VolumeUp,
    VolumeDown,
    AudioStatus(Status),
    SearchResults(Vec<StationRow>),
    SearchFailed(String),
    SetOffline(bool),
    AutoplayStation(StationRow),
    FocusToggle,
    FilterNavNext,
    FilterNavPrev,
    FilterOptionNext,
    FilterOptionPrev,
    FilterApply,
    FilterClear,
    FilterClearAll,
    FacetsLoaded(radio_core::catalog::Facets),
    Tick(std::time::Instant),
    MirrorPlay(radio_core::mirror::MirrorEvent),
    UpdateAvailable(radio_core::update::Release),
    UpdateNow,
}

#[allow(dead_code)]
#[derive(Debug, Clone)]
pub enum Effect {
    Search(SearchQuery, crate::tui::model::BrowseFilters),
    LoadFacets,
    Play(String),
    StopAudio,
    SetVolume(f32),
    SetCrossfade(bool),
    ToggleFavorite(String),
    Blacklist(String),
    Sync,
    SyncCreate,
    SyncLogout,
    SyncDelete,
    Recheck(String),
    RecheckAll,
    RecordHistory(String),
    MarkFailed(String),
    MirrorAnnounce {
        uuid: String,
        name: String,
        url: String,
    },
    SaveState,
    Update(radio_core::update::Release),
}
